spring.application.name=PromptHub

# Base de datos
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Groq
groq.api.key=${groq.api.key}

# Google OAuth
spring.security.oauth2.client.registration.google.client-id=${google_client}
spring.security.oauth2.client.registration.google.client-secret=${google_secret}
spring.security.oauth2.client.registration.google.scope=email,profile

# JWT
app.jwt-secret=${jwt_token}
app.jwt-expiration=86400000
app.frontend-url=http://localhost:5173