package org.example.prompthub.Service;

import lombok.RequiredArgsConstructor;
import org.example.prompthub.DTO.PromptResponseDTO;
import org.example.prompthub.Domain.PromptResponse;
import org.example.prompthub.Domain.User;
import org.example.prompthub.Repository.ResponseRepository;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

@Service
@RequiredArgsConstructor
public class ResponseService {
    private final ResponseRepository repository;
    public List<PromptResponseDTO> getResponsesByUser(User user){
        List<PromptResponse> responses = repository.findByUser(user);
        List<PromptResponseDTO> responseDTOS = new ArrayList<>();
        for (PromptResponse response : responses) {
            PromptResponseDTO responseDTO=convertResponseToDTO(response);
            responseDTOS.add(responseDTO);
        }
        return responseDTOS;

    }
    //only used by PromptService as the responses are autogenerated
    public PromptResponseDTO saveResponse(PromptResponse response){
        repository.save(response);
        return convertResponseToDTO(response);
    }
    public boolean delete(Long id){
        try {
            repository.deleteById(id);
            return true;
        }catch (Exception e){
            return false;
        }
    }


    public PromptResponseDTO convertResponseToDTO(PromptResponse response) {
        PromptResponseDTO resDto = new PromptResponseDTO();
        resDto.setId(response.getId());
        resDto.setModelName(response.getModelName());
        resDto.setOutputContent(response.getOutputContent());
        resDto.setPromptId(response.getPrompt().getId());
        return resDto;
    }

}
